import type { AIModel } from '../types';

export const MODEL_ICON = 'https://img.icons8.com/?size=100&id=77iHQnb2ZTjZ&format=png&color=1A1A1A';

export const AI_MODELS: AIModel[] = [
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'MoSeek Flash',
    description: 'Быстрая и точная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'google/gemma-3-27b-it',
    name: 'MoSeek Gemma',
    description: 'Компактная и умная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-amber-500 to-yellow-600',
  },
  {
    id: 'qwen/qwen3-30b-a3b',
    name: 'MoSeek Qwen',
    description: 'Быстрая модель Qwen3',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-sky-400 to-cyan-500',
  },
  {
    id: 'mistralai/devstral-small',
    name: 'MoSeek Devstral',
    description: 'Модель специально для кода',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-rose-500 to-pink-600',
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'Test 1 — DeepSeek V3',
    description: 'Мощная модель для всех задач',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'Test 2 — DeepSeek R1',
    description: 'Думающая модель с рассуждением',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'deepseek/deepseek-r1-0528',
    name: 'Test 3 — DeepSeek R1 0528',
    description: 'Новейшая версия R1',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-indigo-500 to-violet-600',
  },
  {
    id: 'google/gemini-2.5-flash-preview',
    name: 'Test 4 — Gemini 2.5 Flash',
    description: 'Новейшая быстрая Google',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-emerald-400 to-green-500',
  },
  {
    id: 'google/gemini-2.5-pro-preview',
    name: 'Test 5 — Gemini 2.5 Pro',
    description: 'Самая мощная Google',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'google/gemini-2.5-flash-preview:thinking',
    name: 'Test 6 — Gemini 2.5 Flash Thinking',
    description: 'Flash с цепочкой рассуждений',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-teal-400 to-emerald-500',
  },
  {
    id: 'meta-llama/llama-4-maverick',
    name: 'Test 7 — Llama 4 Maverick',
    description: 'Креативная модель Meta',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-orange-500 to-red-600',
  },
  {
    id: 'meta-llama/llama-4-scout',
    name: 'Test 8 — Llama 4 Scout',
    description: 'Быстрая разведчик Meta',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-orange-400 to-amber-500',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Test 9 — Llama 3.3 70B',
    description: 'Классика Meta 70B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-red-400 to-orange-500',
  },
  {
    id: 'qwen/qwen3-235b-a22b',
    name: 'Test 10 — Qwen3 235B',
    description: 'Гигантская 235B для кода',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-sky-500 to-blue-600',
  },
  {
    id: 'qwen/qwen3-32b',
    name: 'Test 11 — Qwen3 32B',
    description: 'Средняя Qwen3 32B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-400 to-sky-500',
  },
  {
    id: 'qwen/qwen3-14b',
    name: 'Test 12 — Qwen3 14B',
    description: 'Компактная Qwen3 14B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-cyan-400 to-sky-500',
  },
  {
    id: 'qwen/qwen3-8b',
    name: 'Test 13 — Qwen3 8B',
    description: 'Легковесная Qwen3 8B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-300 to-cyan-400',
  },
  {
    id: 'microsoft/mai-ds-r1',
    name: 'Test 14 — Microsoft MAI-R1',
    description: 'Microsoft рассуждающая',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'microsoft/phi-4',
    name: 'Test 15 — Microsoft Phi-4',
    description: 'Компактная Microsoft Phi-4',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-indigo-400 to-blue-500',
  },
  {
    id: 'microsoft/phi-4-reasoning-plus',
    name: 'Test 16 — Phi-4 Reasoning Plus',
    description: 'Phi-4 с рассуждением',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-violet-400 to-indigo-500',
  },
  {
    id: 'mistralai/mistral-small-3.1-24b-instruct',
    name: 'Test 17 — Mistral Small 3.1',
    description: 'Mistral Small 24B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-pink-400 to-rose-500',
  },
  {
    id: 'mistralai/mistral-nemo',
    name: 'Test 18 — Mistral Nemo',
    description: 'Mistral Nemo 12B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-rose-400 to-pink-500',
  },
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    name: 'Test 19 — Nemotron 70B',
    description: 'NVIDIA Nemotron 70B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-green-500 to-lime-500',
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1',
    name: 'Test 20 — Nemotron Super 49B',
    description: 'NVIDIA Nemotron Super',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-lime-500 to-green-500',
  },
  {
    id: 'moonshotai/kimi-k2',
    name: 'Test 21 — Kimi K2',
    description: 'Moonshot Kimi K2',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-purple-400 to-fuchsia-500',
  },
  {
    id: 'nousresearch/hermes-3-llama-3.1-405b',
    name: 'Test 22 — Hermes 3 405B',
    description: 'Огромная Hermes 405B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-amber-400 to-orange-500',
  },
  {
    id: 'nousresearch/deephermes-3-llama-3-8b-preview',
    name: 'Test 23 — DeepHermes 3 8B',
    description: 'Компактная Hermes 8B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-yellow-400 to-amber-500',
  },
  {
    id: 'open-r1/olympiccoder-32b',
    name: 'Test 24 — OlympicCoder 32B',
    description: 'Модель для олимпиадного кода',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-yellow-500 to-orange-500',
  },
  {
    id: 'cognitivecomputations/dolphin3.0-r1-mistral-24b',
    name: 'Test 25 — Dolphin 3.0 R1',
    description: 'Dolphin без цензуры 24B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-300 to-indigo-400',
  },
  {
    id: 'cognitivecomputations/dolphin3.0-mistral-24b',
    name: 'Test 26 — Dolphin 3.0',
    description: 'Dolphin Mistral 24B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-indigo-300 to-blue-400',
  },
  {
    id: 'google/gemma-3-4b-it',
    name: 'Test 27 — Gemma 3 4B',
    description: 'Мини Gemma 4B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-amber-300 to-yellow-400',
  },
  {
    id: 'google/gemma-3-12b-it',
    name: 'Test 28 — Gemma 3 12B',
    description: 'Средняя Gemma 12B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-yellow-400 to-amber-400',
  },
  {
    id: 'deepseek/deepseek-prover-v2',
    name: 'Test 29 — DeepSeek Prover V2',
    description: 'Математическая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-purple-500 to-violet-600',
  },
  {
    id: 'deepseek/deepseek-v3-0324',
    name: 'Test 30 — DeepSeek V3 0324',
    description: 'DeepSeek V3 мартовская',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-violet-400 to-purple-500',
  },
  {
    id: 'qwen/qwen3-0.6b',
    name: 'Test 31 — Qwen3 0.6B',
    description: 'Ультралёгкая Qwen 0.6B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-slate-400 to-zinc-500',
  },
  {
    id: 'qwen/qwen3-1.7b',
    name: 'Test 32 — Qwen3 1.7B',
    description: 'Микро Qwen 1.7B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-zinc-400 to-slate-500',
  },
  {
    id: 'qwen/qwen3-4b',
    name: 'Test 33 — Qwen3 4B',
    description: 'Мини Qwen 4B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-sky-300 to-blue-400',
  },
  {
    id: 'qwen/qwen2.5-72b-instruct',
    name: 'Test 34 — Qwen 2.5 72B',
    description: 'Большая Qwen 2.5 72B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'qwen/qwen2.5-vl-72b-instruct',
    name: 'Test 35 — Qwen 2.5 VL 72B',
    description: 'Qwen 2.5 с vision 72B',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'qwen/qwen2.5-coder-32b-instruct',
    name: 'Test 36 — Qwen 2.5 Coder 32B',
    description: 'Qwen специально для кода',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-teal-400 to-cyan-500',
  },
  {
    id: 'mistralai/mistral-large',
    name: 'Test 37 — Mistral Large',
    description: 'Большая модель Mistral',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-fuchsia-400 to-pink-500',
  },
  {
    id: 'mistralai/codestral-2501',
    name: 'Test 38 — Codestral',
    description: 'Mistral для кода',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-pink-500 to-fuchsia-500',
  },
  {
    id: 'thudm/glm-4-32b',
    name: 'Test 39 — GLM-4 32B',
    description: 'Tsinghua GLM-4',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-red-400 to-rose-500',
  },
  {
    id: 'thudm/glm-z1-32b',
    name: 'Test 40 — GLM-Z1 32B',
    description: 'GLM рассуждающая',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-rose-400 to-red-500',
  },
];

export const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
