import type { AIModel } from '../types';

export const MODEL_ICON = 'https://img.icons8.com/?size=100&id=77iHQnb2ZTjZ&format=png&color=1A1A1A';

export const AI_MODELS: AIModel[] = [
  {
    id: 'stepfun/step-3.5-flash:free',
    name: 'MoSeek Step 3.5',
    description: 'Step 3.5 Flash — быстрая и точная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-cyan-400 to-blue-500',
  },
  {
    id: 'google/gemma-3-27b-it:free',
    name: 'MoSeek Gemma 3 27B',
    description: 'Google Gemma 3 27B — мощная открытая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-400 to-indigo-500',
  },
  {
    id: 'google/gemma-3-12b-it:free',
    name: 'MoSeek Gemma 3 12B',
    description: 'Google Gemma 3 12B — сбалансированная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-indigo-400 to-purple-500',
  },
  {
    id: 'google/gemma-3-4b-it:free',
    name: 'MoSeek Gemma 3 4B',
    description: 'Google Gemma 3 4B — лёгкая и быстрая',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-purple-400 to-pink-500',
  },
  {
    id: 'google/gemma-3-1b-it:free',
    name: 'MoSeek Gemma 3 1B',
    description: 'Google Gemma 3 1B — ультралёгкая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-pink-400 to-rose-500',
  },
  {
    id: 'meta-llama/llama-4-maverick:free',
    name: 'MoSeek Llama 4 Maverick',
    description: 'Meta Llama 4 Maverick — новейшая модель Meta',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-500 to-cyan-400',
  },
  {
    id: 'meta-llama/llama-4-scout:free',
    name: 'MoSeek Llama 4 Scout',
    description: 'Meta Llama 4 Scout — эффективная и умная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-teal-400 to-emerald-500',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'MoSeek Llama 3.3 70B',
    description: 'Meta Llama 3.3 70B — топовая открытая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-emerald-400 to-green-500',
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct:free',
    name: 'MoSeek Llama 3.1 8B',
    description: 'Meta Llama 3.1 8B — компактная и быстрая',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-green-400 to-lime-500',
  },
  {
    id: 'qwen/qwen3-235b-a22b:free',
    name: 'MoSeek Qwen 3 235B',
    description: 'Qwen 3 235B — огромная MoE модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-violet-400 to-purple-600',
  },
  {
    id: 'qwen/qwen3-32b:free',
    name: 'MoSeek Qwen 3 32B',
    description: 'Qwen 3 32B — мощная и точная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-purple-500 to-violet-600',
  },
  {
    id: 'qwen/qwen3-30b-a3b:free',
    name: 'MoSeek Qwen 3 30B',
    description: 'Qwen 3 30B A3B — эффективная MoE модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-fuchsia-400 to-purple-500',
  },
  {
    id: 'qwen/qwen3-14b:free',
    name: 'MoSeek Qwen 3 14B',
    description: 'Qwen 3 14B — сбалансированная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-rose-400 to-red-500',
  },
  {
    id: 'qwen/qwen3-8b:free',
    name: 'MoSeek Qwen 3 8B',
    description: 'Qwen 3 8B — быстрая и умная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-orange-400 to-amber-500',
  },
  {
    id: 'qwen/qwen3-4b:free',
    name: 'MoSeek Qwen 3 4B',
    description: 'Qwen 3 4B — лёгкая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-amber-400 to-yellow-500',
  },
  {
    id: 'qwen/qwen3-1.7b:free',
    name: 'MoSeek Qwen 3 1.7B',
    description: 'Qwen 3 1.7B — минималистичная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-yellow-400 to-lime-500',
  },
  {
    id: 'qwen/qwen3-0.6b:free',
    name: 'MoSeek Qwen 3 0.6B',
    description: 'Qwen 3 0.6B — ультракомпактная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-lime-400 to-green-400',
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct:free',
    name: 'MoSeek Qwen 2.5 72B',
    description: 'Qwen 2.5 72B — топовая модель Qwen 2.5',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-sky-400 to-blue-600',
  },
  {
    id: 'qwen/qwen-2.5-vl-72b-instruct:free',
    name: 'MoSeek Qwen 2.5 VL 72B',
    description: 'Qwen 2.5 VL 72B — мультимодальная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'qwen/qwen-2.5-vl-32b-instruct:free',
    name: 'MoSeek Qwen 2.5 VL 32B',
    description: 'Qwen 2.5 VL 32B — мультимодальная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-teal-500 to-cyan-600',
  },
  {
    id: 'qwen/qwq-32b:free',
    name: 'MoSeek QwQ 32B',
    description: 'QwQ 32B — модель с рассуждениями (reasoning)',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-red-400 to-orange-500',
  },
  {
    id: 'deepseek/deepseek-r1-0528:free',
    name: 'MoSeek DeepSeek R1',
    description: 'DeepSeek R1 0528 — мощная reasoning модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-slate-400 to-gray-600',
  },
  {
    id: 'deepseek/deepseek-chat-v3-0324:free',
    name: 'MoSeek DeepSeek V3',
    description: 'DeepSeek Chat V3 — продвинутый чат',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-gray-400 to-slate-600',
  },
  {
    id: 'deepseek/deepseek-r1-distill-llama-70b:free',
    name: 'MoSeek DeepSeek R1 Llama 70B',
    description: 'DeepSeek R1 Distill Llama 70B — дистилляция',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-zinc-400 to-neutral-600',
  },
  {
    id: 'microsoft/mai-ds-r1:free',
    name: 'MoSeek MAI DS R1',
    description: 'Microsoft MAI DS R1 — модель от Microsoft',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-blue-400 to-sky-600',
  },
  {
    id: 'microsoft/phi-4-reasoning-plus:free',
    name: 'MoSeek Phi 4 Reasoning+',
    description: 'Microsoft Phi 4 Reasoning Plus — рассуждения',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-sky-400 to-indigo-500',
  },
  {
    id: 'microsoft/phi-4-reasoning:free',
    name: 'MoSeek Phi 4 Reasoning',
    description: 'Microsoft Phi 4 Reasoning — компактная reasoning',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-indigo-400 to-blue-600',
  },
  {
    id: 'mistralai/mistral-small-3.1-24b-instruct:free',
    name: 'MoSeek Mistral Small 3.1',
    description: 'Mistral Small 3.1 24B — быстрая и точная',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'mistralai/devstral-small:free',
    name: 'MoSeek Devstral Small',
    description: 'Devstral Small — модель для разработки',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-red-500 to-pink-600',
  },
  {
    id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1:free',
    name: 'MoSeek Nemotron Ultra 253B',
    description: 'NVIDIA Nemotron Ultra 253B — сверхмощная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1:free',
    name: 'MoSeek Nemotron Super 49B',
    description: 'NVIDIA Nemotron Super 49B — продвинутая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'moonshotai/kimi-vl-a3b-thinking:free',
    name: 'MoSeek Kimi VL Thinking',
    description: 'Kimi VL A3B Thinking — мультимодальная с рассуждениями',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-violet-500 to-indigo-600',
  },
  {
    id: 'nousresearch/hermes-3-llama-3.1-405b:free',
    name: 'MoSeek Hermes 3 405B',
    description: 'Hermes 3 Llama 3.1 405B — крупнейшая открытая модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'rekaai/reka-flash-3:free',
    name: 'MoSeek Reka Flash 3',
    description: 'Reka Flash 3 — быстрая мультимодальная модель',
    provider: 'MoGPT',
    icon: MODEL_ICON,
    color: 'from-pink-500 to-fuchsia-600',
  },
];

export const DEFAULT_MODEL = 'stepfun/step-3.5-flash:free';

export const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
